# Generated by Django 3.1.1 on 2023-09-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20230914_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('position',)},
        ),
    ]
